/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.thingml.xtext.ui.AbstractThingMLUiModule;
import org.thingml.xtext.ui.ThingMLAntlrTokenToAttributeIdMapper;
import org.thingml.xtext.ui.ThingMLHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ThingMLUiModule extends AbstractThingMLUiModule {
  public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    return ThingMLAntlrTokenToAttributeIdMapper.class;
  }
  
  public Class<? extends DefaultHighlightingConfiguration> bindDefaultHighlightingConfiguration() {
    return ThingMLHighlightingConfiguration.class;
  }
  
  public ThingMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
