/**
 * generated by Xtext 2.9.1
 */
package org.thingml.xtext;

import org.thingml.xtext.ThingMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ThingMLStandaloneSetup extends ThingMLStandaloneSetupGenerated {
  public static void doSetup() {
    ThingMLStandaloneSetup _thingMLStandaloneSetup = new ThingMLStandaloneSetup();
    _thingMLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
