/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext;

import org.thingml.xtext.AbstractThingMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ThingMLRuntimeModule extends AbstractThingMLRuntimeModule {
}
