/**
 * Copyright (C) 2011 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * File generated by the ThingML IDE /!\Do not edit this file/!\ In case of a
 * bug in the generated code, please submit an issue on our GitHub
 *
 */
package org.thingml.generated;

import org.thingml.generated.*;
import org.sintef.smac.*;
import org.kevoree.annotation.*;
import org.kevoree.framework.*;
import org.thingml.generated.*;

@Provides({
    @ProvidedPort(name = "kv2thingML_client_port", type = PortType.MESSAGE)})
@ComponentType
public class Kv2ThingML_client extends AbstractComponentType {

    Client thingML_client_component = new Client(new String(), new String(), new String(), (short) 0, (short) 0, new String(), new String());

    @Start
    public void startComponent() {
    }

    @Stop
    public void stopComponent() {
    }

    @Update
    public void updateComponent() {
    }

    @Port(name = "kv2thingML_client_port")
    public void kv2thingML_client_port(Object o) {
        if (o instanceof RRequest) {
            RRequest rcv_RRequest = (RRequest) o;
            kv2thingML_client_port.getPort("kv2thingML_client_port").get().send(rcv_RRequest);
        }
        if (o instanceof InputID) {
            InputID rcv_InputID = (InputID) o;
            kv2thingML_client_port.getPort("kv2thingML_client_port").get().send(rcv_InputID);
        }
        if (o instanceof TypeRequest) {
            TypeRequest rcv_TypeRequest = (TypeRequest) o;
            kv2thingML_client_port.getPort("kv2thingML_client_port").get().send(rcv_TypeRequest);
        }
        if (o instanceof Number) {
            Number rcv_Number = (Number) o;
            kv2thingML_client_port.getPort("kv2thingML_client_port").get().send(rcv_Number);
        }
    }
}
