/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.thingML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Internal Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getInternalTransition()
 * @model
 * @generated
 */
public interface InternalTransition extends Handler
{
} // InternalTransition
