/*
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ThingMLRuntimeModule extends AbstractThingMLRuntimeModule {
	
    override Class<? extends IValueConverterService> bindIValueConverterService() {
            return ThingMLTerminalConverter;
    }
    
}
