@startuml
skinparam defaultTextAlignment left
caption Behavior of thing HelloThing
[*] --> HelloStateChart
state HelloStateChart{
state HelloState_1{
	HelloState_1 : entry / println "Hello World!"\n
}
HelloState_1 --> [*]
[*] --> HelloState_1
}
@enduml
