/**
 * generated by Xtext 2.9.1
 */
package org.thingml.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.thingml.xtext.ui.AbstractThingMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ThingMLUiModule extends AbstractThingMLUiModule {
  public ThingMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
