/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.ecore.EClass;

import org.thingml.xtext.thingML.RegionOrSession;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Region Or Session</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RegionOrSessionImpl extends RegionImpl implements RegionOrSession
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RegionOrSessionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.Literals.REGION_OR_SESSION;
  }

} //RegionOrSessionImpl
