/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.serializer;

import org.thingml.xtext.serializer.AbstractThingMLSemanticSequencer;

@SuppressWarnings("all")
public class ThingMLSemanticSequencer extends AbstractThingMLSemanticSequencer {
}
