@startuml
skinparam defaultTextAlignment left
caption Behavior of thing Countdown
[*] --> default
state default{
state Counting{
	Counting : entry / do...end

Counting --> Counting : e:timer?timer_timeout\naction current = current - 1\n

Counting --> Stopped : [current == 0]\naction timer!timer_cancel(TimerID)\n
}
state Stopped{
	Stopped : entry / println "Stopped."\n
}
Stopped --> [*]
[*] --> Counting
}
@enduml
