@startuml
caption Datatypes used in configuration CountdownUML
class UInt16 <<(D,#D2E524)2>> {
}
note bottom of UInt16 : <b>@type_checker</b> <color:royalBlue>"Integer"</color>\n<b>@c_type</b> <color:royalBlue>"uint16_t"</color>\n<b>@c_byte_size</b> <color:royalBlue>"2"</color>\n<b>@java_type</b> <color:royalBlue>"int"</color>\n<b>@js_type</b> <color:royalBlue>"int"</color>\n<b>@java_primitive</b> <color:royalBlue>"true"</color>\n<b>@go_type</b> <color:royalBlue>"uint16"</color>\n
class UInt8 <<(D,#D2E524)1>> {
}
note bottom of UInt8 : <b>@type_checker</b> <color:royalBlue>"Integer"</color>\n<b>@c_type</b> <color:royalBlue>"uint8_t"</color>\n<b>@c_byte_size</b> <color:royalBlue>"1"</color>\n<b>@java_type</b> <color:royalBlue>"short"</color>\n<b>@js_type</b> <color:royalBlue>"short"</color>\n<b>@java_primitive</b> <color:royalBlue>"true"</color>\n<b>@go_type</b> <color:royalBlue>"uint8"</color>\n
class JSArray <<(O,#E5D224)>> {
}
@enduml