@startuml
skinparam defaultTextAlignment left
caption Behavior of thing TimerJava
[*] --> SoftTimer
state SoftTimer{
state default_4{
	default_4 : m:timer?timer_start / [m.time > 0]\naction startTimer(...)\n
	default_4 : m:timer?timer_cancel / \naction cancel(m.id)\n
}
[*] --> default_4
}
@enduml
