#define /*MESSAGE_NAME_UPPER*/_/*STREAM_NAME_UPPER*/_TTL /*MESSAGE_TTL*/
#define /*MESSAGE_NAME_UPPER*/_NUMBER_MSG     /*NUMBER_MESSAGE*/
#define /*MESSAGE_NAME_UPPER*/_ELEMENT_SIZE   (TIMESTAMP_DATASIZE + /*STRUCT_SIZE*/)
#define /*MESSAGE_NAME_UPPER*/_FIFO_SIZE      ((/*MESSAGE_NAME_UPPER*/_NUMBER_MSG * /*MESSAGE_NAME_UPPER*/_ELEMENT_SIZE) + 1)
