@startuml
skinparam defaultTextAlignment left
caption Behavior of thing PingClient
[*] --> PingClientMachine
state PingClientMachine{
state Ping{
	Ping : entry / do...end
	Ping : exit / counter = counter + 1\n

Ping --> OK : e:ping_service?pong[e.seq == counter]\naction println "[OK]"\n

Ping --> Stop : e:ping_service?pong[e.seq != counter]\naction println "[Error]"\n
}
state OK{

OK --> Stop : [counter > 5]

OK --> Ping : [counter <= 5]
}
state Stop{
	Stop : entry / println "Bye."\n
}
Stop --> [*]
[*] --> Ping
}
@enduml
