@startuml
skinparam defaultTextAlignment left
caption Behavior of thing PingServer
[*] --> default
state default{
state Active{

Active --> Active : m:ping_service?ping\naction ping_service!pong(m.seq)\n
}
[*] --> Active
}
@enduml
