/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.validation;

import org.thingml.xtext.validation.AbstractThingMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ThingMLValidator extends AbstractThingMLValidator {
}
