/*
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import thingml.ui.internal.ThingmlActivator;

public class ThingMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ThingmlActivator.getInstance().getInjector("org.thingml.xtext.ThingML");
	}

}
