/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.thingML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotated Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getAnnotatedElement()
 * @model
 * @generated
 */
public interface AnnotatedElement extends EObject
{
} // AnnotatedElement
