/**
 * Copyright (C) 2014 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * generated by Xtext 2.9.1
 */
package org.thingml.xtext.thingML;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Session</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.thingml.xtext.thingML.StartSession#getSession <em>Session</em>}</li>
 *   <li>{@link org.thingml.xtext.thingML.StartSession#getConstructor <em>Constructor</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.thingml.xtext.thingML.ThingMLPackage#getStartSession()
 * @model
 * @generated
 */
public interface StartSession extends Action
{
  /**
   * Returns the value of the '<em><b>Session</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Session</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Session</em>' reference.
   * @see #setSession(Session)
   * @see org.thingml.xtext.thingML.ThingMLPackage#getStartSession_Session()
   * @model
   * @generated
   */
  Session getSession();

  /**
   * Sets the value of the '{@link org.thingml.xtext.thingML.StartSession#getSession <em>Session</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Session</em>' reference.
   * @see #getSession()
   * @generated
   */
  void setSession(Session value);

  /**
   * Returns the value of the '<em><b>Constructor</b></em>' containment reference list.
   * The list contents are of type {@link org.thingml.xtext.thingML.PropertyAssign}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constructor</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructor</em>' containment reference list.
   * @see org.thingml.xtext.thingML.ThingMLPackage#getStartSession_Constructor()
   * @model containment="true"
   * @generated
   */
  EList<PropertyAssign> getConstructor();

} // StartSession
