package org.thingml.externalthingplugins.c.posix.dnssd.strategies;

import org.sintef.thingml.Thing;
import org.thingml.compilers.DebugProfile;
import org.thingml.compilers.c.CCompilerContext;
import org.thingml.compilers.interfaces.c.ICThingApiStructStrategy;

/**
 * Created by vassik on 04.11.16.
 */
public class PosixThingApiStructDNSSDStrategy implements ICThingApiStructStrategy {

    private String protocalName;

    public PosixThingApiStructDNSSDStrategy(String _protocalName) {
        protocalName = _protocalName;
    };

    @Override
    public void generateInstanceStruct(Thing thing, StringBuilder builder, CCompilerContext ctx, DebugProfile debugProfile) {

        builder.append(protocalName + "related properties, generated by '"+this.getClass().getSimpleName() +"' \n");

        builder.append("DNSSDAvahiService * service_data;");

        builder.append("DNSSDThreadedAhvaiClient * avahi_client;");
    }
}
