/**
 * Copyright (C) 2014 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingml.externalthingplugins.c.posix.dnssd.strategies;

import org.sintef.thingml.Thing;
import org.thingml.compilers.DebugProfile;
import org.thingml.compilers.c.CCompilerContext;
import org.thingml.compilers.interfaces.c.ICThingApiStructStrategy;
import org.thingml.externalthingplugins.c.posix.PosixDNSSDExternalThingPlugin;

/**
 * Created by vassik on 04.11.16.
 */
public class PosixThingApiStructDNSSDStrategy implements ICThingApiStructStrategy {

    private PosixDNSSDExternalThingPlugin plugin;

    public PosixThingApiStructDNSSDStrategy(PosixDNSSDExternalThingPlugin _plugin) {
        plugin = _plugin;
    };

    @Override
    public void generateInstanceStruct(Thing thing, StringBuilder builder, CCompilerContext ctx, DebugProfile debugProfile) {

        builder.append("// "+ plugin.getProtocolName()+ " related properties, generated by '" + this.getClass().getSimpleName() + "' \n");

        builder.append(plugin.getProtocolName() + "AvahiService * service_data; \n");

        builder.append(plugin.getProtocolName() + "ThreadedAhvaiClient * avahi_client; \n");
    }
}
