package org.thingml.externalthingplugins.c.posix.dnssd.strategies;

import org.sintef.thingml.Thing;
import org.thingml.compilers.DebugProfile;
import org.thingml.compilers.c.CCompilerContext;
import org.thingml.compilers.interfaces.c.ICThingApiStructStrategy;
import org.thingml.externalthingplugins.c.posix.PosixDNSSDExternalThingPlugin;

/**
 * Created by vassik on 04.11.16.
 */
public class PosixThingApiStructDNSSDStrategy implements ICThingApiStructStrategy {

    private PosixDNSSDExternalThingPlugin plugin;

    public PosixThingApiStructDNSSDStrategy(PosixDNSSDExternalThingPlugin _plugin) {
        plugin = _plugin;
    };

    @Override
    public void generateInstanceStruct(Thing thing, StringBuilder builder, CCompilerContext ctx, DebugProfile debugProfile) {

        builder.append("// "+ plugin.getProtocolName()+ " related properties, generated by '"+this.getClass().getSimpleName() +"' \n");

        builder.append(plugin.getProtocolName() + "AvahiService * service_data;");

        builder.append(plugin.getProtocolName() + "ThreadedAhvaiClient * avahi_client;");
    }
}
