/**
 * Copyright (C) 2014 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingml.externalthingplugins.c.posix.dnssd.strategies;

import org.sintef.thingml.Thing;
import org.thingml.compilers.c.CCompilerContext;
import org.thingml.compilers.interfaces.c.ICThingApiIncludesStrategy;
import org.thingml.externalthingplugins.c.posix.PosixDNSSDExternalThingPlugin;

/**
 * Created by vassik on 16.11.16.
 */
public class PosixThingApiIncludesStrategy implements ICThingApiIncludesStrategy {

    PosixDNSSDExternalThingPlugin plugin;

    public PosixThingApiIncludesStrategy(PosixDNSSDExternalThingPlugin _plugin) {
        plugin = _plugin;
    }

    @Override
    public void generateIncludes(Thing thing, StringBuilder builder, CCompilerContext ctx) {
        builder.append("// Adding DNSSD includes. Generated by: " + this.getClass().getSimpleName() + "\n");

        builder.append("#include \"" + plugin.getProtocolName() + ".h\"\n\n");
    }
}
