/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.ecore.EClass;

import org.thingml.xtext.thingML.LengthArray;
import org.thingml.xtext.thingML.ThingMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Length Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LengthArrayImpl extends ElmtPropertyImpl implements LengthArray
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LengthArrayImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.Literals.LENGTH_ARRAY;
  }

} //LengthArrayImpl
