/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.thingML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.thingml.xtext.thingML.ThingMLPackage;
import org.thingml.xtext.thingML.ViewSource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>View Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ViewSourceImpl extends MinimalEObjectImpl.Container implements ViewSource
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ViewSourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ThingMLPackage.Literals.VIEW_SOURCE;
  }

} //ViewSourceImpl
