/**
 * generated by Xtext 2.10.0
 */
package org.thingml.xtext.ui.labeling;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.thingml.xtext.thingML.CompositeState;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ThingMLLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public ThingMLLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final CompositeState sm) {
    String _xblockexpression = null;
    {
      String result = "[SM";
      String _name = sm.getName();
      boolean _notEquals = (!Objects.equal(_name, null));
      if (_notEquals) {
        String _result = result;
        String _name_1 = sm.getName();
        String _plus = (" " + _name_1);
        result = (_result + _plus);
      }
      String _result_1 = result;
      _xblockexpression = result = (_result_1 + "]");
    }
    return _xblockexpression;
  }
}
