@startuml
caption Instances and Connectors in configuration Robot
component [motion : MotionControl]<<PIM>>
component [robot : RobotControl]<<PIM>>
component [left_wheel : WheelControl]<<PIM>>
component [scoll : CollisionSensor]<<PIM>>
component [sdist : DistanceSensor]<<PIM>>
component [right_wheel : WheelControl]<<PIM>>
[robot : RobotControl] -(0- [scoll : CollisionSensor] : bumper => data
[motion : MotionControl] -(0- [right_wheel : WheelControl] : right => ctrl
[robot : RobotControl] -(0- [sdist : DistanceSensor] : rangefinder => data
[robot : RobotControl] -(0- [motion : MotionControl] : platform => ctrl
[motion : MotionControl] -(0- [left_wheel : WheelControl] : left => ctrl
@enduml