@startuml
caption Instances and Connectors in configuration Robot
component [scoll : CollisionSensor]<<PIM>>
component [robot : RobotControl]<<PIM>>
component [motion : MotionControl]<<PIM>>
component [right_wheel : WheelControl]<<PIM>>
component [sdist : DistanceSensor]<<PIM>>
component [left_wheel : WheelControl]<<PIM>>
motion -(0- right_wheel : right => ctrl
motion -(0- left_wheel : left => ctrl
robot -(0- scoll : bumper => data
robot -(0- sdist : rangefinder => data
robot -(0- motion : platform => ctrl
@enduml